# Generated by Django 6.0.3 on 2026-04-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateAuthority',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('signature_image', models.ImageField(upload_to='signatures/')),
            ],
            options={
                'db_table': 'certificate_authorities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OtpserviceTrainees',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('roll_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'otpService_trainees',
                'managed': True,
            },
        ),
    ]
