# Generated by Django 6.0.3 on 2026-04-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myLoginSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificateauthority',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='otpservicetrainees',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
