# Generated by Django 6.0.3 on 2026-04-21 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myLoginSystem', '0002_alter_certificateauthority_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificateauthority',
            options={'managed': True},
        ),
    ]
